### ISSUE TITLE
Problem with permission even with `setenforce 0`

### ISSUE THREAD

**Issue by soimy** [wigcheng/kotlin_gpiod_demo#1]
First, Thanks for the demo, great works!

I'm testing this approach on OrangePi 5(Very popular recently), Android 12 [link](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-pi-5.html)
It compile and run successfully, and I followed the instruction to set proper permission `0666` on `/dev/gpiochip*`, then `setenforce 0`, but with some suspicious error log:
```
I/m.example.gpiod: type=1400 audit(0.0:1924): avc: denied { read write } for name="gpiochip0" dev="tmpfs" ino=366 scontext=u:r:untrusted_app:s0:c107,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1 app=com.example.gpiod
I/m.example.gpiod: type=1400 audit(0.0:1925): avc: denied { open } for path="/dev/gpiochip0" dev="tmpfs" ino=366 scontext=u:r:untrusted_app:s0:c107,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1 app=com.example.gpiod
W/audit: audit_lost=1588 audit_rate_limit=5 audit_backlog_limit=64
E/audit: rate limit exceeded
I/m.example.gpiod: type=1400 audit(0.0:1926): avc: denied { getattr } for path="/dev/gpiochip0" dev="tmpfs" ino=366 scontext=u:r:untrusted_app:s0:c107,c256,c512,c768 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1 app=com.example.gpiod
I/m.example.gpiod: type=1400 audit(0.0:1927): avc: denied { read } for name="dev" dev="sysfs" ino=16518 scontext=u:r:untrusted_app:s0:c107,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1 app=com.example.gpiod
I/m.example.gpiod: type=1400 audit(0.0:1928): avc: denied { open } for path="/sys/devices/platform/fd8a0000.gpio/gpiochip0/dev" dev="sysfs" ino=16518 scontext=u:r:untrusted_app:s0:c107,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1 app=com.example.gpiod
D/gpiod-lib_JNI: set gpio ret = 0
D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10107; state: ENABLED
D/gpiod-lib_JNI: GPIO gpiobank is 2
D/gpiod-lib_JNI: GPIO gpioline is 26
D/gpiod-lib_JNI: set gpio ret = 0
D/gpiod-lib_JNI: GPIO gpiobank is 2
D/gpiod-lib_JNI: GPIO gpioline is 26
```

In the test, I set the GPIO2-D2 to `low`, which should be gpiochip2, line 27(?), but once read the pin, it always show `1` as a result. From the log it seems tmpfs open/read/write is denied.

Help needed, thx.

**Comment by wigcheng** [comment]
According to your log, it seems set gpio value successfully without error (ret =0), so I think the problem could be control the wrong GPIO pin.

You can use those commands to check which specific GPIO pin you want control:
gpiod way
`# gpioinfo`
sysfs way
`# cat /sys/kernel/debug/gpio`

In addition, it's a gpiod feature:
Get value only can be used on GPIO "Input" pin.
Set value only can be used on GPIO "Output" pin.
So if you calling get value after set value immediately, that GPIO pin will change back to Input pin :)

Summary your problem.
1. Checking your specific pin already be define as GPIO
2. Checking correct GPIO number of that pin you want to control.
3. Setting GPIO output value
4. If you want to check the value is right, please use 'cat /sys/kernel/debug/gpio', don't use gpiod get function in APK (It's for input pin only).

Thanks!

**Comment by soimy** [comment]
Thanks for the info! It's really helpful.
Based on your reply, I tested using a 5-pin LED Press button (3 Pin switch with NO/NC + 2 Pin LED).
Connected as this diagram:
![WX20230227-134041@2x](https://user-images.githubusercontent.com/1550237/221483537-ba5e3a29-98e5-4877-ae55-d838c956dcc8.png)

I can control the LED with the Red line GPIO pin's 3.3v logic HIGH/LOW with no problem.
But the Green line's GPIO Input is always LOW no matter I press the button or not. (Confirmed gpio pin is at inpurt mode)

Using Orangepi's official WiringOP android, input/output all working properly.

BTW: How to get gpiod command line tool installed in Android?

**Comment by wigcheng** [comment]
So, your GPIO output issue was solved using this demo app, right?

For your GPIO input issue, you can check logcat to see get value function is successful or not, a quick way is use  'cat /sys/kernel/debug/gpio' again, and observing the specific pin when you press and release button, it should be show "hi" or "low" dynamicially. If this pin can be changed, it means pinmux setting is correct, then please check logcat again, maybe it's gpiod bug, please let me know, then I'll check it later.

gpiod get function was be implemented using gpioget command.

Thanks

**Comment by soimy** [comment]
It just mysteriously runs OK when I recompile and run this demo on Android studio mac...
Thank you so much for the help.
